---
name: "eslint"
description: "eslint by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: "--color"
runs:
  using: "docker"
  image: docker://pipelinecomponents/eslint
  args:
    - eslint
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
